In [87]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [88]:
df = pd.read_csv('covid - Copy.csv')
df

,Sno,Date,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths
0,1,30-01-2020,Kerala,1,0,0,0
1,2,01-02-2020,Kerala,2,0,0,0
2,3,02-02-2020,Kerala,3,0,0,0
3,4,02-03-2020,Telengana,1,0,0,0
4,5,02-03-2020,Delhi,1,0,0,0
5,6,03-03-2020,Rajasthan,0,1,0,0
6,7,03-03-2020,Kerala,3,0,3,0
7,8,04-03-2020,Uttar Pradesh,6,0,0,0
8,9,04-03-2020,Haryana,0,2,0,0
9,10,04-03-2020,Rajasthan,1,14,0,0
10,11,05-03-2020,Delhi,2,0,0,0
11,12,05-03-2020,Uttar Pradesh,7,0,0,0
12,13,06-03-2020,Delhi,3,0,0,0
13,14,06-03-2020,Rajasthan,1,14,0,0
14,15,07-03-2020,Union Territory of Ladakh,2,0,0,0
15,16,07-03-2020,Tamil Nadu,1,0,0,0
16,17,07-03-2020,Delhi,3,0,0,0
17,18,08-03-2020,Kerala,8,0,3,0
18,19,08-03-2020,Haryana,0,2,0,0
19,20,08-03-2020,Uttar Pradesh,7,0,0,0
20,21,09-03-2020,Karnataka,1,0,0,0
21,22,09-03-2020,Maharashtra,2,0,0,0
22,23,09-03-2020,Punjab,1,0,0,0
23,24,09-03-2020,Union Territory of Jammu and Kashmir,1,0,0,0
24,25,10-03-2020,Kerala,15,0,3,0
25,26,10-03-2020,Maharashtra,5,0,0,0
26,27,10-03-2020,Karnataka,4,0,0,0
27,28,11-03-2020,Maharashtra,2,0,0,0
28,29,11-03-2020,Delhi,5,0,0,0
29,30,11-03-2020,Karnataka,4,0,0,0
30,31,12-03-2020,Uttar Pradesh,10,1,0,0
31,32,12-03-2020,Union Territory of Ladakh,3,0,0,0
32,33,12-03-2020,Maharashtra,11,0,0,0
33,34,12-03-2020,Andhra Pradesh,1,0,0,0
34,35,13-03-2020,Karnataka,6,0,0,1
35,36,13-03-2020,Maharashtra,14,0,0,0
36,37,14-03-2020,Delhi,7,0,1,1
37,38,14-03-2020,Uttar Pradesh,11,1,5,0
38,39,14-03-2020,Union Territory of Jammu and Kashmir,2,0,0,0
39,40,15-03-2020,Maharashtra,32,0,0,0
40,41,15-03-2020,Rajasthan,2,2,3,0
41,42,15-03-2020,Telengana,3,0,1,0
42,43,15-03-2020,Uttarakhand,1,0,0,0
43,44,16-03-2020,Odisha,1,0,0,0
44,45,16-03-2020,Union Territory of Ladakh,4,0,0,0
45,46,17-03-2020,Maharashtra,36,3,0,1
46,47,17-03-2020,Telengana,3,2,1,0
47,48,18-03-2020,Pondicherry,1,0,0,0
48,49,19-03-2020,Gujarat,5,0,0,0
49,50,20-03-2020,West Bengal,2,0,0,0

In [89]:
label_encoder = LabelEncoder()
print(label_encoder)

LabelEncoder()

In [90]:
df['State/UnionTerritory'] = label_encoder.fit_transform(df['State/UnionTerritory'])
df['Date'] = label_encoder.fit_transform(df['Date'])

In [91]:
df

,Sno,Date,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths
0,1,21,5,1,0,0,0
1,2,0,5,2,0,0,0
2,3,1,5,3,0,0,0
3,4,2,12,1,0,0,0
4,5,2,1,1,0,0,0
5,6,3,10,0,1,0,0
6,7,3,5,3,0,3,0
7,8,4,15,6,0,0,0
8,9,4,3,0,2,0,0
9,10,4,10,1,14,0,0
10,11,5,1,2,0,0,0
11,12,5,15,7,0,0,0
12,13,6,1,3,0,0,0
13,14,6,10,1,14,0,0
14,15,7,14,2,0,0,0
15,16,7,11,1,0,0,0
16,17,7,1,3,0,0,0
17,18,8,5,8,0,3,0
18,19,8,3,0,2,0,0
19,20,8,15,7,0,0,0
20,21,9,4,1,0,0,0
21,22,9,6,2,0,0,0
22,23,9,9,1,0,0,0
23,24,9,13,1,0,0,0
24,25,10,5,15,0,3,0
25,26,10,6,5,0,0,0
26,27,10,4,4,0,0,0
27,28,11,6,2,0,0,0
28,29,11,1,5,0,0,0
29,30,11,4,4,0,0,0
30,31,12,15,10,1,0,0
31,32,12,14,3,0,0,0
32,33,12,6,11,0,0,0
33,34,12,0,1,0,0,0
34,35,13,4,6,0,0,1
35,36,13,6,14,0,0,0
36,37,14,1,7,0,1,1
37,38,14,15,11,1,5,0
38,39,14,13,2,0,0,0
39,40,15,6,32,0,0,0
40,41,15,10,2,2,3,0
41,42,15,12,3,0,1,0
42,43,15,16,1,0,0,0
43,44,16,7,1,0,0,0
44,45,16,14,4,0,0,0
45,46,17,6,36,3,0,1
46,47,17,12,3,2,1,0
47,48,18,8,1,0,0,0
48,49,19,2,5,0,0,0
49,50,20,17,2,0,0,0

In [92]:
X = df.drop(['ConfirmedForeignNational','Deaths'], axis=1)
print(X)
y = df['Deaths']
print(y)

    Sno  Date  State/UnionTerritory  ConfirmedIndianNational  Cured
0     1    21                     5                        1      0
1     2     0                     5                        2      0
2     3     1                     5                        3      0
3     4     2                    12                        1      0
4     5     2                     1                        1      0
5     6     3                    10                        0      0
6     7     3                     5                        3      3
7     8     4                    15                        6      0
8     9     4                     3                        0      0
9    10     4                    10                        1      0
10   11     5                     1                        2      0
11   12     5                    15                        7      0
12   13     6                     1                        3      0
13   14     6                    10                        1      0
14   15     7                    14                        2      0
15   16     7                    11                        1      0
16   17     7                     1                        3      0
17   18     8                     5                        8      3
18   19     8                     3                        0      0
19   20     8                    15                        7      0
20   21     9                     4                        1      0
21   22     9                     6                        2      0
22   23     9                     9                        1      0
23   24     9                    13                        1      0
24   25    10                     5                       15      3
25   26    10                     6                        5      0
26   27    10                     4                        4      0
27   28    11                     6                        2      0
28   29    11                     1                        5      0
29   30    11                     4                        4      0
30   31    12                    15                       10      0
31   32    12                    14                        3      0
32   33    12                     6                       11      0
33   34    12                     0                        1      0
34   35    13                     4                        6      0
35   36    13                     6                       14      0
36   37    14                     1                        7      1
37   38    14                    15                       11      5
38   39    14                    13                        2      0
39   40    15                     6                       32      0
40   41    15                    10                        2      3
41   42    15                    12                        3      1
42   43    15                    16                        1      0
43   44    16                     7                        1      0
44   45    16                    14                        4      0
45   46    17                     6                       36      0
46   47    17                    12                        3      1
47   48    18                     8                        1      0
48   49    19                     2                        5      0
49   50    20                    17                        2      0
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    1
35    0
36    1
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    1
46    0
47    0
48    0
49    0
Name: Deaths, dtype: int64

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [94]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [95]:
a=model.predict([[5,2,1,1,0]])
#a = np.array(model.predict([[0,34,1]]))

C:\Users\Student\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [96]:
a

array([0])

In [97]:
original_data = label_encoder.inverse_transform(a)

In [98]:
original_data

array(['01-02-2020'], dtype=object)

In [99]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 80.00%